/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.formula1.view;

import com.mycompany.formula1.controller.DriverController;
import com.mycompany.formula1.controller.DriverTeamController;
import com.mycompany.formula1.controller.TeamController;
import com.mycompany.formula1.model.Driver;
import com.mycompany.formula1.model.Team;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adrian
 */
public class MainScreen extends javax.swing.JFrame {
    private final TeamController teamController = new TeamController();
    private final DriverController driverController = new DriverController();
    private final DriverTeamController driverTeamController = new DriverTeamController();
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        updateTeamsTable();
        updateDriversTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teamTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        driverTable = new javax.swing.JTable();
        addTeam = new javax.swing.JButton();
        removeTeam = new javax.swing.JButton();
        updateTeam = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addDriver = new javax.swing.JButton();
        updateDriver = new javax.swing.JButton();
        removeDriver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome da Equipe", "Pais"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(teamTable);

        driverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Indentificação", "Piloto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(driverTable);

        addTeam.setText("Adicionar Equipe");
        addTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamActionPerformed(evt);
            }
        });

        removeTeam.setText("Remover Equipe");
        removeTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTeamActionPerformed(evt);
            }
        });

        updateTeam.setText("Atualizar Equipe");
        updateTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeamActionPerformed(evt);
            }
        });

        jButton1.setText("Ver Pilotos da Equipe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addDriver.setText("Adicionar Piloto");
        addDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriverActionPerformed(evt);
            }
        });

        updateDriver.setText("Atualizar Piloto");
        updateDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDriverActionPerformed(evt);
            }
        });

        removeDriver.setText("Remover Piloto");
        removeDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDriverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(updateTeam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addTeam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                    .addComponent(removeTeam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(addTeam)
                        .addGap(18, 18, 18)
                        .addComponent(updateTeam))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addDriver)
                        .addGap(18, 18, 18)
                        .addComponent(updateDriver)
                        .addGap(18, 18, 18)
                        .addComponent(removeDriver)))
                .addGap(18, 18, 18)
                .addComponent(removeTeam)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamActionPerformed
        updateDriversTable();
        updateTeamsTable();
    }//GEN-LAST:event_addTeamActionPerformed

    private void removeTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTeamActionPerformed

        int selectedRow = teamTable.getSelectedRow();
			
      if (selectedRow != -1) {
        int teamId = (int) teamTable.getValueAt(selectedRow, 0); //Pego o valor da celula que corresponde a linha tal x coluna tal

        try {
            teamController.removeTeam(teamId);
        } catch (Exception e) {
            showErrorMessage(e.getMessage());
        }
      } else {
		showErrorMessage("Selecione uma Equipe!");
      }
        
        updateTeamsTable();
    }//GEN-LAST:event_removeTeamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDriverActionPerformed

    private void updateDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateDriverActionPerformed

    private void removeDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDriverActionPerformed
	int selectedRow = driverTable.getSelectedRow();
			
	if (selectedRow != -1) {
		int driverId = (int) driverTable.getValueAt(selectedRow, 0); //Pego o valor da celula que corresponde a linha tal x coluna tal

		try {
			driverController.deleteDriver(driverId);
		} catch (Exception e) {
			showErrorMessage(e.getMessage());
		}
	} else {
		showErrorMessage("Selecione um Piloto!");
	}
        updateDriversTable();
    }//GEN-LAST:event_removeDriverActionPerformed

    private void updateTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTeamActionPerformed

    
    private void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(null, message, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    public void updateTeamsTable() {
        try {
            List<Team> teamList = teamController.getAllTeams(); // ou listarTeams()
            DefaultTableModel model = (DefaultTableModel) teamTable.getModel();
            model.setRowCount(0); // limpa a tabela

            for (Team team : teamList) {
                Object[] rowData = {team.getId(), team.getName(), team.getCountry()};
                model.addRow(rowData);
            }
        } catch (Exception e) {
            showErrorMessage(e.getMessage());
        }
    }

    public void updateDriversTable() {
        try {
        List<Driver> driverList = driverController.getAllDrivers(); // ou listarDrivers()
        DefaultTableModel model = (DefaultTableModel) driverTable.getModel();
        model.setRowCount(0); // limpa a tabela

        for (Driver driver : driverList) {
            Object[] rowData = {driver.getId(), driver.getName(), driver.getTeamId()};
            model.addRow(rowData);
        }
        } catch (Exception e) {
           showErrorMessage(e.getMessage());
         }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDriver;
    private javax.swing.JButton addTeam;
    private javax.swing.JTable driverTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeDriver;
    private javax.swing.JButton removeTeam;
    private javax.swing.JTable teamTable;
    private javax.swing.JButton updateDriver;
    private javax.swing.JButton updateTeam;
    // End of variables declaration//GEN-END:variables
}
